// Mocks generated by Mockito 5.4.6 from annotations
// in ml_algo/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i57;
import 'dart:collection' as _i47;
import 'dart:io' as _i16;

import 'package:ml_algo/src/classifier/classifier.dart' as _i54;
import 'package:ml_algo/src/classifier/decision_tree_classifier/decision_tree_classifier.dart'
    as _i10;
import 'package:ml_algo/src/classifier/decision_tree_classifier/decision_tree_classifier_factory.dart'
    as _i44;
import 'package:ml_algo/src/classifier/knn_classifier/knn_classifier.dart'
    as _i19;
import 'package:ml_algo/src/classifier/knn_classifier/knn_classifier_factory.dart'
    as _i61;
import 'package:ml_algo/src/classifier/logistic_regressor/logistic_regressor.dart'
    as _i29;
import 'package:ml_algo/src/classifier/logistic_regressor/logistic_regressor_factory.dart'
    as _i79;
import 'package:ml_algo/src/classifier/softmax_regressor/softmax_regressor.dart'
    as _i30;
import 'package:ml_algo/src/classifier/softmax_regressor/softmax_regressor_factory.dart'
    as _i75;
import 'package:ml_algo/src/common/distribution_calculator/distribution_calculator.dart'
    as _i13;
import 'package:ml_algo/src/common/distribution_calculator/distribution_calculator_factory.dart'
    as _i49;
import 'package:ml_algo/src/cost_function/cost_function.dart' as _i9;
import 'package:ml_algo/src/cost_function/cost_function_factory.dart' as _i41;
import 'package:ml_algo/src/cost_function/cost_function_type.dart' as _i42;
import 'package:ml_algo/src/knn_kernel/kernel.dart' as _i18;
import 'package:ml_algo/src/knn_kernel/kernel_factory.dart' as _i60;
import 'package:ml_algo/src/knn_kernel/kernel_type.dart' as _i59;
import 'package:ml_algo/src/knn_solver/knn_solver.dart' as _i17;
import 'package:ml_algo/src/knn_solver/knn_solver_factory.dart' as _i58;
import 'package:ml_algo/src/knn_solver/neigbour.dart' as _i56;
import 'package:ml_algo/src/linear_optimizer/convergence_detector/convergence_detector.dart'
    as _i22;
import 'package:ml_algo/src/linear_optimizer/convergence_detector/convergence_detector_factory.dart'
    as _i65;
import 'package:ml_algo/src/linear_optimizer/gradient_optimizer/learning_rate/learning_rate_iterable_factory.dart'
    as _i50;
import 'package:ml_algo/src/linear_optimizer/gradient_optimizer/learning_rate/learning_rate_type.dart'
    as _i51;
import 'package:ml_algo/src/linear_optimizer/initial_coefficients_generator/initial_coefficients_generator.dart'
    as _i12;
import 'package:ml_algo/src/linear_optimizer/initial_coefficients_generator/initial_coefficients_generator_factory.dart'
    as _i45;
import 'package:ml_algo/src/linear_optimizer/initial_coefficients_generator/initial_coefficients_type.dart'
    as _i46;
import 'package:ml_algo/src/linear_optimizer/linear_optimizer.dart' as _i21;
import 'package:ml_algo/src/linear_optimizer/linear_optimizer_factory.dart'
    as _i62;
import 'package:ml_algo/src/linear_optimizer/linear_optimizer_type.dart'
    as _i63;
import 'package:ml_algo/src/linear_optimizer/regularization_type.dart' as _i64;
import 'package:ml_algo/src/link_function/link_function.dart' as _i28;
import 'package:ml_algo/src/math/randomizer/randomizer.dart' as _i7;
import 'package:ml_algo/src/math/randomizer/randomizer_factory.dart' as _i40;
import 'package:ml_algo/src/metric/metric.dart' as _i6;
import 'package:ml_algo/src/metric/metric_factory.dart' as _i38;
import 'package:ml_algo/src/metric/metric_type.dart' as _i39;
import 'package:ml_algo/src/model_selection/assessable.dart' as _i68;
import 'package:ml_algo/src/model_selection/model_assessor/classifier_assessor.dart'
    as _i53;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider.dart'
    as _i23;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider_factory.dart'
    as _i66;
import 'package:ml_algo/src/model_selection/split_indices_provider/split_indices_provider_type.dart'
    as _i67;
import 'package:ml_algo/src/persistence/tree_store.dart' as _i78;
import 'package:ml_algo/src/predictor/predictor.dart' as _i76;
import 'package:ml_algo/src/regressor/knn_regressor/knn_regressor.dart' as _i27;
import 'package:ml_algo/src/regressor/knn_regressor/knn_regressor_factory.dart'
    as _i74;
import 'package:ml_algo/src/regressor/linear_regressor/linear_regressor.dart'
    as _i31;
import 'package:ml_algo/src/regressor/linear_regressor/linear_regressor_factory.dart'
    as _i77;
import 'package:ml_algo/src/tree_trainer/decision_tree_trainer.dart' as _i73;
import 'package:ml_algo/src/tree_trainer/leaf_detector/leaf_detector.dart'
    as _i15;
import 'package:ml_algo/src/tree_trainer/leaf_detector/leaf_detector_factory.dart'
    as _i52;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label.dart' as _i14;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory.dart'
    as _i24;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory_factory.dart'
    as _i69;
import 'package:ml_algo/src/tree_trainer/leaf_label/leaf_label_factory_type.dart'
    as _i70;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector.dart'
    as _i25;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector_factory.dart'
    as _i71;
import 'package:ml_algo/src/tree_trainer/split_selector/split_selector_type.dart'
    as _i72;
import 'package:ml_algo/src/tree_trainer/splitter/nominal_splitter/nominal_splitter.dart'
    as _i3;
import 'package:ml_algo/src/tree_trainer/splitter/nominal_splitter/nominal_splitter_factory.dart'
    as _i33;
import 'package:ml_algo/src/tree_trainer/splitter/numerical_splitter/numerical_splitter.dart'
    as _i2;
import 'package:ml_algo/src/tree_trainer/splitter/numerical_splitter/numerical_splitter_factory.dart'
    as _i32;
import 'package:ml_algo/src/tree_trainer/splitter/splitter.dart' as _i5;
import 'package:ml_algo/src/tree_trainer/splitter/splitter_factory.dart'
    as _i36;
import 'package:ml_algo/src/tree_trainer/splitter/splitter_type.dart' as _i37;
import 'package:ml_algo/src/tree_trainer/tree_assessor/tree_assessor.dart'
    as _i4;
import 'package:ml_algo/src/tree_trainer/tree_assessor/tree_assessor_factory.dart'
    as _i34;
import 'package:ml_algo/src/tree_trainer/tree_assessor/tree_assessor_type.dart'
    as _i35;
import 'package:ml_algo/src/tree_trainer/tree_node/tree_node.dart' as _i26;
import 'package:ml_dataframe/ml_dataframe.dart' as _i20;
import 'package:ml_linalg/distance.dart' as _i55;
import 'package:ml_linalg/dtype.dart' as _i43;
import 'package:ml_linalg/matrix.dart' as _i8;
import 'package:ml_linalg/vector.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i48;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNumericalTreeSplitter_0 extends _i1.SmartFake
    implements _i2.NumericalTreeSplitter {
  _FakeNumericalTreeSplitter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNominalTreeSplitter_1 extends _i1.SmartFake
    implements _i3.NominalTreeSplitter {
  _FakeNominalTreeSplitter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeAssessor_2 extends _i1.SmartFake implements _i4.TreeAssessor {
  _FakeTreeAssessor_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeSplitter_3 extends _i1.SmartFake implements _i5.TreeSplitter {
  _FakeTreeSplitter_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetric_4 extends _i1.SmartFake implements _i6.Metric {
  _FakeMetric_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRandomizer_5 extends _i1.SmartFake implements _i7.Randomizer {
  _FakeRandomizer_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatrix_6 extends _i1.SmartFake implements _i8.Matrix {
  _FakeMatrix_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCostFunction_7 extends _i1.SmartFake implements _i9.CostFunction {
  _FakeCostFunction_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecisionTreeClassifier_8 extends _i1.SmartFake
    implements _i10.DecisionTreeClassifier {
  _FakeDecisionTreeClassifier_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVector_9 extends _i1.SmartFake implements _i11.Vector {
  _FakeVector_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInitialCoefficientsGenerator_10 extends _i1.SmartFake
    implements _i12.InitialCoefficientsGenerator {
  _FakeInitialCoefficientsGenerator_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDistributionCalculator_11 extends _i1.SmartFake
    implements _i13.DistributionCalculator {
  _FakeDistributionCalculator_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeLeafLabel_12 extends _i1.SmartFake
    implements _i14.TreeLeafLabel {
  _FakeTreeLeafLabel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeLeafDetector_13 extends _i1.SmartFake
    implements _i15.TreeLeafDetector {
  _FakeTreeLeafDetector_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_14 extends _i1.SmartFake implements _i16.File {
  _FakeFile_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnnSolver_15 extends _i1.SmartFake implements _i17.KnnSolver {
  _FakeKnnSolver_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKernel_16 extends _i1.SmartFake implements _i18.Kernel {
  _FakeKernel_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnnClassifier_17 extends _i1.SmartFake
    implements _i19.KnnClassifier {
  _FakeKnnClassifier_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataFrame_18 extends _i1.SmartFake implements _i20.DataFrame {
  _FakeDataFrame_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    int? maxRows = 10,
    int? maxCols = 7,
  }) =>
      super.toString();
}

class _FakeLinearOptimizer_19 extends _i1.SmartFake
    implements _i21.LinearOptimizer {
  _FakeLinearOptimizer_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConvergenceDetector_20 extends _i1.SmartFake
    implements _i22.ConvergenceDetector {
  _FakeConvergenceDetector_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSplitIndicesProvider_21 extends _i1.SmartFake
    implements _i23.SplitIndicesProvider {
  _FakeSplitIndicesProvider_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeLeafLabelFactory_22 extends _i1.SmartFake
    implements _i24.TreeLeafLabelFactory {
  _FakeTreeLeafLabelFactory_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeSplitSelector_23 extends _i1.SmartFake
    implements _i25.TreeSplitSelector {
  _FakeTreeSplitSelector_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTreeNode_24 extends _i1.SmartFake implements _i26.TreeNode {
  _FakeTreeNode_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKnnRegressor_25 extends _i1.SmartFake implements _i27.KnnRegressor {
  _FakeKnnRegressor_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinkFunction_26 extends _i1.SmartFake implements _i28.LinkFunction {
  _FakeLinkFunction_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogisticRegressor_27 extends _i1.SmartFake
    implements _i29.LogisticRegressor {
  _FakeLogisticRegressor_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSoftmaxRegressor_28 extends _i1.SmartFake
    implements _i30.SoftmaxRegressor {
  _FakeSoftmaxRegressor_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinearRegressor_29 extends _i1.SmartFake
    implements _i31.LinearRegressor {
  _FakeLinearRegressor_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NumericalTreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumericalTreeSplitterFactory extends _i1.Mock
    implements _i32.NumericalTreeSplitterFactory {
  MockNumericalTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NumericalTreeSplitter create() => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
        ),
        returnValue: _FakeNumericalTreeSplitter_0(
          this,
          Invocation.method(
            #create,
            [],
          ),
        ),
      ) as _i2.NumericalTreeSplitter);
}

/// A class which mocks [NominalTreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockNominalTreeSplitterFactory extends _i1.Mock
    implements _i33.NominalTreeSplitterFactory {
  MockNominalTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NominalTreeSplitter create() => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
        ),
        returnValue: _FakeNominalTreeSplitter_1(
          this,
          Invocation.method(
            #create,
            [],
          ),
        ),
      ) as _i3.NominalTreeSplitter);
}

/// A class which mocks [TreeAssessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeAssessor extends _i1.Mock implements _i4.TreeAssessor {
  MockTreeAssessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getAggregatedError(
    Iterable<_i8.Matrix>? split,
    int? targetIdx,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAggregatedError,
          [
            split,
            targetIdx,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double getError(
    _i8.Matrix? samples,
    int? targetIdx,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getError,
          [
            samples,
            targetIdx,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [TreeAssessorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeAssessorFactory extends _i1.Mock
    implements _i34.TreeAssessorFactory {
  MockTreeAssessorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TreeAssessor createByType(_i35.TreeAssessorType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [type],
        ),
        returnValue: _FakeTreeAssessor_2(
          this,
          Invocation.method(
            #createByType,
            [type],
          ),
        ),
      ) as _i4.TreeAssessor);
}

/// A class which mocks [NumericalTreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumericalTreeSplitter extends _i1.Mock
    implements _i2.NumericalTreeSplitter {
  MockNumericalTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i26.TreeNode, _i8.Matrix> split(
    _i8.Matrix? samples,
    int? splittingIdx,
    double? splittingValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #split,
          [
            samples,
            splittingIdx,
            splittingValue,
          ],
        ),
        returnValue: <_i26.TreeNode, _i8.Matrix>{},
      ) as Map<_i26.TreeNode, _i8.Matrix>);
}

/// A class which mocks [NominalTreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockNominalTreeSplitter extends _i1.Mock
    implements _i3.NominalTreeSplitter {
  MockNominalTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i26.TreeNode, _i8.Matrix> split(
    _i8.Matrix? samples,
    int? splittingIdx,
    List<num>? uniqueValues,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #split,
          [
            samples,
            splittingIdx,
            uniqueValues,
          ],
        ),
        returnValue: <_i26.TreeNode, _i8.Matrix>{},
      ) as Map<_i26.TreeNode, _i8.Matrix>);
}

/// A class which mocks [TreeSplitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitter extends _i1.Mock implements _i5.TreeSplitter {
  MockTreeSplitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i26.TreeNode, _i8.Matrix> split(
    _i8.Matrix? samples,
    int? splittingIdx,
    int? targetId, [
    List<num>? uniqueValues,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #split,
          [
            samples,
            splittingIdx,
            targetId,
            uniqueValues,
          ],
        ),
        returnValue: <_i26.TreeNode, _i8.Matrix>{},
      ) as Map<_i26.TreeNode, _i8.Matrix>);
}

/// A class which mocks [TreeSplitterFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitterFactory extends _i1.Mock
    implements _i36.TreeSplitterFactory {
  MockTreeSplitterFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TreeSplitter createByType(
    _i37.TreeSplitterType? type,
    _i35.TreeAssessorType? assessorType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [
            type,
            assessorType,
          ],
        ),
        returnValue: _FakeTreeSplitter_3(
          this,
          Invocation.method(
            #createByType,
            [
              type,
              assessorType,
            ],
          ),
        ),
      ) as _i5.TreeSplitter);
}

/// A class which mocks [MetricFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricFactory extends _i1.Mock implements _i38.MetricFactory {
  MockMetricFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Metric createByType(_i39.MetricType? metricType) => (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [metricType],
        ),
        returnValue: _FakeMetric_4(
          this,
          Invocation.method(
            #createByType,
            [metricType],
          ),
        ),
      ) as _i6.Metric);
}

/// A class which mocks [Metric].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetric extends _i1.Mock implements _i6.Metric {
  MockMetric() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getScore(
    _i8.Matrix? predictedLabels,
    _i8.Matrix? origLabels,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScore,
          [
            predictedLabels,
            origLabels,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [RandomizerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomizerFactory extends _i1.Mock implements _i40.RandomizerFactory {
  MockRandomizerFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Randomizer create([int? seed]) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [seed],
        ),
        returnValue: _FakeRandomizer_5(
          this,
          Invocation.method(
            #create,
            [seed],
          ),
        ),
      ) as _i7.Randomizer);
}

/// A class which mocks [Randomizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomizer extends _i1.Mock implements _i7.Randomizer {
  MockRandomizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<int> getIntegerInterval(
    int? lowerBound,
    int? upperBound, {
    int? intervalLength,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntegerInterval,
          [
            lowerBound,
            upperBound,
          ],
          {#intervalLength: intervalLength},
        ),
        returnValue: <int>[],
      ) as Iterable<int>);

  @override
  Iterable<double> getDoubleInterval(
    double? lowerBound,
    double? upperBound,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoubleInterval,
          [
            lowerBound,
            upperBound,
          ],
        ),
        returnValue: <double>[],
      ) as Iterable<double>);

  @override
  int getIntegerFromInterval(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntegerFromInterval,
          [
            start,
            end,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  double getDoubleFromInterval(
    double? start,
    double? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoubleFromInterval,
          [
            start,
            end,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [CostFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockCostFunction extends _i1.Mock implements _i9.CostFunction {
  MockCostFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double getCost(
    _i8.Matrix? x,
    _i8.Matrix? w,
    _i8.Matrix? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCost,
          [
            x,
            w,
            y,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Matrix getGradient(
    _i8.Matrix? x,
    _i8.Matrix? w,
    _i8.Matrix? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGradient,
          [
            x,
            w,
            y,
          ],
        ),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.method(
            #getGradient,
            [
              x,
              w,
              y,
            ],
          ),
        ),
      ) as _i8.Matrix);

  @override
  _i8.Matrix getHessian(
    _i8.Matrix? x,
    _i8.Matrix? w,
    _i8.Matrix? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHessian,
          [
            x,
            w,
            y,
          ],
        ),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.method(
            #getHessian,
            [
              x,
              w,
              y,
            ],
          ),
        ),
      ) as _i8.Matrix);
}

/// A class which mocks [CostFunctionFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCostFunctionFactory extends _i1.Mock
    implements _i41.CostFunctionFactory {
  MockCostFunctionFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.CostFunction createByType(
    _i42.CostFunctionType? type, {
    _i28.LinkFunction? linkFunction,
    num? positiveLabel,
    num? negativeLabel,
    _i43.DType? dtype,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [type],
          {
            #linkFunction: linkFunction,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel,
            #dtype: dtype,
          },
        ),
        returnValue: _FakeCostFunction_7(
          this,
          Invocation.method(
            #createByType,
            [type],
            {
              #linkFunction: linkFunction,
              #positiveLabel: positiveLabel,
              #negativeLabel: negativeLabel,
              #dtype: dtype,
            },
          ),
        ),
      ) as _i9.CostFunction);
}

/// A class which mocks [DecisionTreeClassifierFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeClassifierFactory extends _i1.Mock
    implements _i44.DecisionTreeClassifierFactory {
  MockDecisionTreeClassifierFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.DecisionTreeClassifier create(
    _i20.DataFrame? trainData,
    String? targetName,
    _i43.DType? dtype,
    num? minError,
    int? minSamplesCount,
    int? maxDepth,
    _i35.TreeAssessorType? assessorType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            trainData,
            targetName,
            dtype,
            minError,
            minSamplesCount,
            maxDepth,
            assessorType,
          ],
        ),
        returnValue: _FakeDecisionTreeClassifier_8(
          this,
          Invocation.method(
            #create,
            [
              trainData,
              targetName,
              dtype,
              minError,
              minSamplesCount,
              maxDepth,
              assessorType,
            ],
          ),
        ),
      ) as _i10.DecisionTreeClassifier);

  @override
  _i10.DecisionTreeClassifier fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeDecisionTreeClassifier_8(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i10.DecisionTreeClassifier);
}

/// A class which mocks [LinkFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkFunction extends _i1.Mock implements _i28.LinkFunction {
  MockLinkFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Matrix link(_i8.Matrix? scoresByClasses) => (super.noSuchMethod(
        Invocation.method(
          #link,
          [scoresByClasses],
        ),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.method(
            #link,
            [scoresByClasses],
          ),
        ),
      ) as _i8.Matrix);
}

/// A class which mocks [InitialCoefficientsGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitialCoefficientsGenerator extends _i1.Mock
    implements _i12.InitialCoefficientsGenerator {
  MockInitialCoefficientsGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Vector generate(int? length) => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [length],
        ),
        returnValue: _FakeVector_9(
          this,
          Invocation.method(
            #generate,
            [length],
          ),
        ),
      ) as _i11.Vector);
}

/// A class which mocks [InitialCoefficientsGeneratorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitialCoefficientsGeneratorFactory extends _i1.Mock
    implements _i45.InitialCoefficientsGeneratorFactory {
  MockInitialCoefficientsGeneratorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.InitialCoefficientsGenerator zeroes(_i43.DType? dtype) =>
      (super.noSuchMethod(
        Invocation.method(
          #zeroes,
          [dtype],
        ),
        returnValue: _FakeInitialCoefficientsGenerator_10(
          this,
          Invocation.method(
            #zeroes,
            [dtype],
          ),
        ),
      ) as _i12.InitialCoefficientsGenerator);

  @override
  _i12.InitialCoefficientsGenerator fromType(
    _i46.InitialCoefficientsType? type,
    _i43.DType? dtype,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromType,
          [
            type,
            dtype,
          ],
        ),
        returnValue: _FakeInitialCoefficientsGenerator_10(
          this,
          Invocation.method(
            #fromType,
            [
              type,
              dtype,
            ],
          ),
        ),
      ) as _i12.InitialCoefficientsGenerator);
}

/// A class which mocks [ConvergenceDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvergenceDetector extends _i1.Mock
    implements _i22.ConvergenceDetector {
  MockConvergenceDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get minDiff => (super.noSuchMethod(
        Invocation.getter(#minDiff),
        returnValue: 0.0,
      ) as double);

  @override
  int get iterationsLimit => (super.noSuchMethod(
        Invocation.getter(#iterationsLimit),
        returnValue: 0,
      ) as int);

  @override
  bool isConverged(
    double? coefficientsDiff,
    int? iteration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isConverged,
          [
            coefficientsDiff,
            iteration,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [DistributionCalculator].
///
/// See the documentation for Mockito's code generation for more information.
class MockDistributionCalculator extends _i1.Mock
    implements _i13.DistributionCalculator {
  MockDistributionCalculator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i47.HashMap<T, double> calculate<T>(
    Iterable<T>? sequence, [
    int? classLabelsLength,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculate,
          [
            sequence,
            classLabelsLength,
          ],
        ),
        returnValue: _i48.dummyValue<_i47.HashMap<T, double>>(
          this,
          Invocation.method(
            #calculate,
            [
              sequence,
              classLabelsLength,
            ],
          ),
        ),
      ) as _i47.HashMap<T, double>);
}

/// A class which mocks [DistributionCalculatorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockDistributionCalculatorFactory extends _i1.Mock
    implements _i49.DistributionCalculatorFactory {
  MockDistributionCalculatorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.DistributionCalculator create() => (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
        ),
        returnValue: _FakeDistributionCalculator_11(
          this,
          Invocation.method(
            #create,
            [],
          ),
        ),
      ) as _i13.DistributionCalculator);
}

/// A class which mocks [LearningRateIterableFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLearningRateIterableFactory extends _i1.Mock
    implements _i50.LearningRateIterableFactory {
  MockLearningRateIterableFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<double> fromType({
    required _i51.LearningRateType? type,
    required double? initialValue,
    required double? decay,
    required int? dropRate,
    required int? iterationLimit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromType,
          [],
          {
            #type: type,
            #initialValue: initialValue,
            #decay: decay,
            #dropRate: dropRate,
            #iterationLimit: iterationLimit,
          },
        ),
        returnValue: <double>[],
      ) as Iterable<double>);
}

/// A class which mocks [TreeLeafDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafDetector extends _i1.Mock implements _i15.TreeLeafDetector {
  MockTreeLeafDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isLeaf(
    _i8.Matrix? sample,
    int? targetIdx,
    Iterable<int>? featureColumnIdxs,
    int? treeDepth,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLeaf,
          [
            sample,
            targetIdx,
            featureColumnIdxs,
            treeDepth,
          ],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [TreeLeafLabelFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafLabelFactory extends _i1.Mock
    implements _i24.TreeLeafLabelFactory {
  MockTreeLeafLabelFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.TreeLeafLabel create(
    _i8.Matrix? samples,
    int? targetIdx,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            samples,
            targetIdx,
          ],
        ),
        returnValue: _FakeTreeLeafLabel_12(
          this,
          Invocation.method(
            #create,
            [
              samples,
              targetIdx,
            ],
          ),
        ),
      ) as _i14.TreeLeafLabel);
}

/// A class which mocks [TreeLeafDetectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafDetectorFactory extends _i1.Mock
    implements _i52.TreeLeafDetectorFactory {
  MockTreeLeafDetectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.TreeLeafDetector create(
    _i35.TreeAssessorType? assessorType,
    num? minErrorOnNode,
    int? minSamplesCount,
    int? maxDepth,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            assessorType,
            minErrorOnNode,
            minSamplesCount,
            maxDepth,
          ],
        ),
        returnValue: _FakeTreeLeafDetector_13(
          this,
          Invocation.method(
            #create,
            [
              assessorType,
              minErrorOnNode,
              minSamplesCount,
              maxDepth,
            ],
          ),
        ),
      ) as _i15.TreeLeafDetector);
}

/// A class which mocks [ClassifierAssessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassifierAssessor extends _i1.Mock
    implements _i53.ClassifierAssessor {
  MockClassifierAssessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double assess(
    _i54.Classifier? classifier,
    _i39.MetricType? metricType,
    _i20.DataFrame? samples,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            classifier,
            metricType,
            samples,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [KnnSolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnSolver extends _i1.Mock implements _i17.KnnSolver {
  MockKnnSolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k => (super.noSuchMethod(
        Invocation.getter(#k),
        returnValue: 0,
      ) as int);

  @override
  _i55.Distance get distanceType => (super.noSuchMethod(
        Invocation.getter(#distanceType),
        returnValue: _i55.Distance.euclidean,
      ) as _i55.Distance);

  @override
  Iterable<Iterable<_i56.Neighbour<_i11.Vector>>> findKNeighbours(
          _i8.Matrix? features) =>
      (super.noSuchMethod(
        Invocation.method(
          #findKNeighbours,
          [features],
        ),
        returnValue: <Iterable<_i56.Neighbour<_i11.Vector>>>[],
      ) as Iterable<Iterable<_i56.Neighbour<_i11.Vector>>>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);
}

/// A class which mocks [KnnSolverFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnSolverFactory extends _i1.Mock implements _i58.KnnSolverFactory {
  MockKnnSolverFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.KnnSolver create(
    _i8.Matrix? trainFeatures,
    _i8.Matrix? trainLabels,
    int? k,
    _i55.Distance? distanceType,
    bool? standardize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            trainFeatures,
            trainLabels,
            k,
            distanceType,
            standardize,
          ],
        ),
        returnValue: _FakeKnnSolver_15(
          this,
          Invocation.method(
            #create,
            [
              trainFeatures,
              trainLabels,
              k,
              distanceType,
              standardize,
            ],
          ),
        ),
      ) as _i17.KnnSolver);
}

/// A class which mocks [Kernel].
///
/// See the documentation for Mockito's code generation for more information.
class MockKernel extends _i1.Mock implements _i18.Kernel {
  MockKernel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i59.KernelType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i59.KernelType.uniform,
      ) as _i59.KernelType);

  @override
  num getWeightByDistance(
    num? distance, [
    num? bandwidth,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeightByDistance,
          [
            distance,
            bandwidth,
          ],
        ),
        returnValue: 0,
      ) as num);

  @override
  String toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: _i48.dummyValue<String>(
          this,
          Invocation.method(
            #toJson,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [KernelFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKernelFactory extends _i1.Mock implements _i60.KernelFactory {
  MockKernelFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Kernel createByType(_i59.KernelType? type) => (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [type],
        ),
        returnValue: _FakeKernel_16(
          this,
          Invocation.method(
            #createByType,
            [type],
          ),
        ),
      ) as _i18.Kernel);
}

/// A class which mocks [KnnClassifierFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnClassifierFactory extends _i1.Mock
    implements _i61.KnnClassifierFactory {
  MockKnnClassifierFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.KnnClassifier create(
    _i20.DataFrame? trainData,
    String? targetName,
    int? k,
    _i59.KernelType? kernelType,
    _i55.Distance? distance,
    String? columnPrefix,
    _i43.DType? dtype,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            trainData,
            targetName,
            k,
            kernelType,
            distance,
            columnPrefix,
            dtype,
          ],
        ),
        returnValue: _FakeKnnClassifier_17(
          this,
          Invocation.method(
            #create,
            [
              trainData,
              targetName,
              k,
              kernelType,
              distance,
              columnPrefix,
              dtype,
            ],
          ),
        ),
      ) as _i19.KnnClassifier);

  @override
  _i19.KnnClassifier fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeKnnClassifier_17(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i19.KnnClassifier);
}

/// A class which mocks [Classifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassifier extends _i1.Mock implements _i54.Classifier {
  MockClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get positiveLabel => (super.noSuchMethod(
        Invocation.getter(#positiveLabel),
        returnValue: 0,
      ) as num);

  @override
  num get negativeLabel => (super.noSuchMethod(
        Invocation.getter(#negativeLabel),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  _i20.DataFrame predictProbabilities(_i20.DataFrame? testFeatures) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictProbabilities,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predictProbabilities,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [LinearOptimizerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearOptimizerFactory extends _i1.Mock
    implements _i62.LinearOptimizerFactory {
  MockLinearOptimizerFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.LinearOptimizer createByType(
    _i63.LinearOptimizerType? optimizerType,
    _i8.Matrix? points,
    _i8.Matrix? labels, {
    required _i43.DType? dtype,
    required _i9.CostFunction? costFunction,
    required _i51.LearningRateType? learningRateType,
    required _i46.InitialCoefficientsType? initialCoefficientsType,
    required double? initialLearningRate,
    required double? decay,
    required int? dropRate,
    required double? minCoefficientsUpdate,
    required int? iterationLimit,
    required double? lambda,
    required int? batchSize,
    required bool? isFittingDataNormalized,
    _i64.RegularizationType? regularizationType,
    int? randomSeed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [
            optimizerType,
            points,
            labels,
          ],
          {
            #dtype: dtype,
            #costFunction: costFunction,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #iterationLimit: iterationLimit,
            #lambda: lambda,
            #batchSize: batchSize,
            #isFittingDataNormalized: isFittingDataNormalized,
            #regularizationType: regularizationType,
            #randomSeed: randomSeed,
          },
        ),
        returnValue: _FakeLinearOptimizer_19(
          this,
          Invocation.method(
            #createByType,
            [
              optimizerType,
              points,
              labels,
            ],
            {
              #dtype: dtype,
              #costFunction: costFunction,
              #learningRateType: learningRateType,
              #initialCoefficientsType: initialCoefficientsType,
              #initialLearningRate: initialLearningRate,
              #decay: decay,
              #dropRate: dropRate,
              #minCoefficientsUpdate: minCoefficientsUpdate,
              #iterationLimit: iterationLimit,
              #lambda: lambda,
              #batchSize: batchSize,
              #isFittingDataNormalized: isFittingDataNormalized,
              #regularizationType: regularizationType,
              #randomSeed: randomSeed,
            },
          ),
        ),
      ) as _i21.LinearOptimizer);
}

/// A class which mocks [LinearOptimizer].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearOptimizer extends _i1.Mock implements _i21.LinearOptimizer {
  MockLinearOptimizer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<num> get costPerIteration => (super.noSuchMethod(
        Invocation.getter(#costPerIteration),
        returnValue: <num>[],
      ) as List<num>);

  @override
  _i8.Matrix findExtrema({
    _i8.Matrix? initialCoefficients,
    bool? isMinimizingObjective = true,
    bool? collectLearningData = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findExtrema,
          [],
          {
            #initialCoefficients: initialCoefficients,
            #isMinimizingObjective: isMinimizingObjective,
            #collectLearningData: collectLearningData,
          },
        ),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.method(
            #findExtrema,
            [],
            {
              #initialCoefficients: initialCoefficients,
              #isMinimizingObjective: isMinimizingObjective,
              #collectLearningData: collectLearningData,
            },
          ),
        ),
      ) as _i8.Matrix);
}

/// A class which mocks [ConvergenceDetectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvergenceDetectorFactory extends _i1.Mock
    implements _i65.ConvergenceDetectorFactory {
  MockConvergenceDetectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.ConvergenceDetector create(
    double? minUpdate,
    int? iterationsLimit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            minUpdate,
            iterationsLimit,
          ],
        ),
        returnValue: _FakeConvergenceDetector_20(
          this,
          Invocation.method(
            #create,
            [
              minUpdate,
              iterationsLimit,
            ],
          ),
        ),
      ) as _i22.ConvergenceDetector);
}

/// A class which mocks [SplitIndicesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplitIndicesProvider extends _i1.Mock
    implements _i23.SplitIndicesProvider {
  MockSplitIndicesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<Iterable<int>> getIndices(int? numberOfSamples) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIndices,
          [numberOfSamples],
        ),
        returnValue: <Iterable<int>>[],
      ) as Iterable<Iterable<int>>);
}

/// A class which mocks [SplitIndicesProviderFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplitIndicesProviderFactory extends _i1.Mock
    implements _i66.SplitIndicesProviderFactory {
  MockSplitIndicesProviderFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.SplitIndicesProvider createByType(
    _i67.SplitIndicesProviderType? splitterType, {
    int? numberOfFolds,
    int? p,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [splitterType],
          {
            #numberOfFolds: numberOfFolds,
            #p: p,
          },
        ),
        returnValue: _FakeSplitIndicesProvider_21(
          this,
          Invocation.method(
            #createByType,
            [splitterType],
            {
              #numberOfFolds: numberOfFolds,
              #p: p,
            },
          ),
        ),
      ) as _i23.SplitIndicesProvider);
}

/// A class which mocks [Assessable].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssessable extends _i1.Mock implements _i68.Assessable {
  MockAssessable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);
}

/// A class which mocks [TreeLeafLabelFactoryFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeLeafLabelFactoryFactory extends _i1.Mock
    implements _i69.TreeLeafLabelFactoryFactory {
  MockTreeLeafLabelFactoryFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.TreeLeafLabelFactory createByType(_i70.TreeLeafLabelFactoryType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [type],
        ),
        returnValue: _FakeTreeLeafLabelFactory_22(
          this,
          Invocation.method(
            #createByType,
            [type],
          ),
        ),
      ) as _i24.TreeLeafLabelFactory);
}

/// A class which mocks [TreeSplitSelector].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitSelector extends _i1.Mock implements _i25.TreeSplitSelector {
  MockTreeSplitSelector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i26.TreeNode, _i8.Matrix> select(
    _i8.Matrix? samples,
    int? targetId,
    Iterable<int>? featuresColumnIdxs, [
    Map<int, List<num>>? columnIdToUniqueValues,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [
            samples,
            targetId,
            featuresColumnIdxs,
            columnIdToUniqueValues,
          ],
        ),
        returnValue: <_i26.TreeNode, _i8.Matrix>{},
      ) as Map<_i26.TreeNode, _i8.Matrix>);
}

/// A class which mocks [TreeSplitSelectorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeSplitSelectorFactory extends _i1.Mock
    implements _i71.TreeSplitSelectorFactory {
  MockTreeSplitSelectorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.TreeSplitSelector createByType(
    _i72.TreeSplitSelectorType? type,
    _i35.TreeAssessorType? assessorType,
    _i37.TreeSplitterType? splitterType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createByType,
          [
            type,
            assessorType,
            splitterType,
          ],
        ),
        returnValue: _FakeTreeSplitSelector_23(
          this,
          Invocation.method(
            #createByType,
            [
              type,
              assessorType,
              splitterType,
            ],
          ),
        ),
      ) as _i25.TreeSplitSelector);
}

/// A class which mocks [TreeNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockTreeNode extends _i1.Mock implements _i26.TreeNode {
  MockTreeNode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLeaf => (super.noSuchMethod(
        Invocation.getter(#isLeaf),
        returnValue: false,
      ) as bool);

  @override
  bool get isRoot => (super.noSuchMethod(
        Invocation.getter(#isRoot),
        returnValue: false,
      ) as bool);

  @override
  bool get isFake => (super.noSuchMethod(
        Invocation.getter(#isFake),
        returnValue: false,
      ) as bool);

  @override
  Map<int, int> get shape => (super.noSuchMethod(
        Invocation.getter(#shape),
        returnValue: <int, int>{},
      ) as Map<int, int>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool testSample(_i11.Vector? sample) => (super.noSuchMethod(
        Invocation.method(
          #testSample,
          [sample],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [DecisionTreeTrainer].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeTrainer extends _i1.Mock
    implements _i73.DecisionTreeTrainer {
  MockDecisionTreeTrainer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.TreeNode train(_i8.Matrix? samples) => (super.noSuchMethod(
        Invocation.method(
          #train,
          [samples],
        ),
        returnValue: _FakeTreeNode_24(
          this,
          Invocation.method(
            #train,
            [samples],
          ),
        ),
      ) as _i26.TreeNode);
}

/// A class which mocks [KnnClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnClassifier extends _i1.Mock implements _i19.KnnClassifier {
  MockKnnClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k => (super.noSuchMethod(
        Invocation.getter(#k),
        returnValue: 0,
      ) as int);

  @override
  _i59.KernelType get kernelType => (super.noSuchMethod(
        Invocation.getter(#kernelType),
        returnValue: _i59.KernelType.uniform,
      ) as _i59.KernelType);

  @override
  _i55.Distance get distanceType => (super.noSuchMethod(
        Invocation.getter(#distanceType),
        returnValue: _i55.Distance.euclidean,
      ) as _i55.Distance);

  @override
  num get positiveLabel => (super.noSuchMethod(
        Invocation.getter(#positiveLabel),
        returnValue: 0,
      ) as num);

  @override
  num get negativeLabel => (super.noSuchMethod(
        Invocation.getter(#negativeLabel),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i19.KnnClassifier retrain(_i20.DataFrame? data) => (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeKnnClassifier_17(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i19.KnnClassifier);

  @override
  _i20.DataFrame predictProbabilities(_i20.DataFrame? testFeatures) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictProbabilities,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predictProbabilities,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [KnnRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnRegressorFactory extends _i1.Mock
    implements _i74.KnnRegressorFactory {
  MockKnnRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i27.KnnRegressor create(
    _i20.DataFrame? fittingData,
    String? targetName,
    int? k,
    _i59.KernelType? kernelType,
    _i55.Distance? distance,
    _i43.DType? dtype,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            fittingData,
            targetName,
            k,
            kernelType,
            distance,
            dtype,
          ],
        ),
        returnValue: _FakeKnnRegressor_25(
          this,
          Invocation.method(
            #create,
            [
              fittingData,
              targetName,
              k,
              kernelType,
              distance,
              dtype,
            ],
          ),
        ),
      ) as _i27.KnnRegressor);

  @override
  _i27.KnnRegressor fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeKnnRegressor_25(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i27.KnnRegressor);
}

/// A class which mocks [KnnRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnnRegressor extends _i1.Mock implements _i27.KnnRegressor {
  MockKnnRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get k => (super.noSuchMethod(
        Invocation.getter(#k),
        returnValue: 0,
      ) as int);

  @override
  _i59.KernelType get kernelType => (super.noSuchMethod(
        Invocation.getter(#kernelType),
        returnValue: _i59.KernelType.uniform,
      ) as _i59.KernelType);

  @override
  _i55.Distance get distanceType => (super.noSuchMethod(
        Invocation.getter(#distanceType),
        returnValue: _i55.Distance.euclidean,
      ) as _i55.Distance);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i27.KnnRegressor retrain(_i20.DataFrame? data) => (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeKnnRegressor_25(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i27.KnnRegressor);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [LogisticRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogisticRegressor extends _i1.Mock implements _i29.LogisticRegressor {
  MockLogisticRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i63.LinearOptimizerType get optimizerType => (super.noSuchMethod(
        Invocation.getter(#optimizerType),
        returnValue: _i63.LinearOptimizerType.gradient,
      ) as _i63.LinearOptimizerType);

  @override
  int get iterationsLimit => (super.noSuchMethod(
        Invocation.getter(#iterationsLimit),
        returnValue: 0,
      ) as int);

  @override
  double get initialLearningRate => (super.noSuchMethod(
        Invocation.getter(#initialLearningRate),
        returnValue: 0.0,
      ) as double);

  @override
  double get decay => (super.noSuchMethod(
        Invocation.getter(#decay),
        returnValue: 0.0,
      ) as double);

  @override
  int get dropRate => (super.noSuchMethod(
        Invocation.getter(#dropRate),
        returnValue: 0,
      ) as int);

  @override
  double get minCoefficientsUpdate => (super.noSuchMethod(
        Invocation.getter(#minCoefficientsUpdate),
        returnValue: 0.0,
      ) as double);

  @override
  num get probabilityThreshold => (super.noSuchMethod(
        Invocation.getter(#probabilityThreshold),
        returnValue: 0,
      ) as num);

  @override
  double get lambda => (super.noSuchMethod(
        Invocation.getter(#lambda),
        returnValue: 0.0,
      ) as double);

  @override
  int get batchSize => (super.noSuchMethod(
        Invocation.getter(#batchSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isFittingDataNormalized => (super.noSuchMethod(
        Invocation.getter(#isFittingDataNormalized),
        returnValue: false,
      ) as bool);

  @override
  _i51.LearningRateType get learningRateType => (super.noSuchMethod(
        Invocation.getter(#learningRateType),
        returnValue: _i51.LearningRateType.decreasingAdaptive,
      ) as _i51.LearningRateType);

  @override
  _i46.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(
        Invocation.getter(#initialCoefficientsType),
        returnValue: _i46.InitialCoefficientsType.zeroes,
      ) as _i46.InitialCoefficientsType);

  @override
  _i28.LinkFunction get linkFunction => (super.noSuchMethod(
        Invocation.getter(#linkFunction),
        returnValue: _FakeLinkFunction_26(
          this,
          Invocation.getter(#linkFunction),
        ),
      ) as _i28.LinkFunction);

  @override
  bool get fitIntercept => (super.noSuchMethod(
        Invocation.getter(#fitIntercept),
        returnValue: false,
      ) as bool);

  @override
  num get interceptScale => (super.noSuchMethod(
        Invocation.getter(#interceptScale),
        returnValue: 0,
      ) as num);

  @override
  _i8.Matrix get coefficientsByClasses => (super.noSuchMethod(
        Invocation.getter(#coefficientsByClasses),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.getter(#coefficientsByClasses),
        ),
      ) as _i8.Matrix);

  @override
  num get positiveLabel => (super.noSuchMethod(
        Invocation.getter(#positiveLabel),
        returnValue: 0,
      ) as num);

  @override
  num get negativeLabel => (super.noSuchMethod(
        Invocation.getter(#negativeLabel),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i29.LogisticRegressor retrain(_i20.DataFrame? data) => (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeLogisticRegressor_27(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i29.LogisticRegressor);

  @override
  _i20.DataFrame predictProbabilities(_i20.DataFrame? testFeatures) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictProbabilities,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predictProbabilities,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [SoftmaxRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftmaxRegressor extends _i1.Mock implements _i30.SoftmaxRegressor {
  MockSoftmaxRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i63.LinearOptimizerType get optimizerType => (super.noSuchMethod(
        Invocation.getter(#optimizerType),
        returnValue: _i63.LinearOptimizerType.gradient,
      ) as _i63.LinearOptimizerType);

  @override
  int get iterationsLimit => (super.noSuchMethod(
        Invocation.getter(#iterationsLimit),
        returnValue: 0,
      ) as int);

  @override
  double get initialLearningRate => (super.noSuchMethod(
        Invocation.getter(#initialLearningRate),
        returnValue: 0.0,
      ) as double);

  @override
  double get decay => (super.noSuchMethod(
        Invocation.getter(#decay),
        returnValue: 0.0,
      ) as double);

  @override
  int get dropRate => (super.noSuchMethod(
        Invocation.getter(#dropRate),
        returnValue: 0,
      ) as int);

  @override
  double get minCoefficientsUpdate => (super.noSuchMethod(
        Invocation.getter(#minCoefficientsUpdate),
        returnValue: 0.0,
      ) as double);

  @override
  double get lambda => (super.noSuchMethod(
        Invocation.getter(#lambda),
        returnValue: 0.0,
      ) as double);

  @override
  int get batchSize => (super.noSuchMethod(
        Invocation.getter(#batchSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isFittingDataNormalized => (super.noSuchMethod(
        Invocation.getter(#isFittingDataNormalized),
        returnValue: false,
      ) as bool);

  @override
  _i51.LearningRateType get learningRateType => (super.noSuchMethod(
        Invocation.getter(#learningRateType),
        returnValue: _i51.LearningRateType.decreasingAdaptive,
      ) as _i51.LearningRateType);

  @override
  _i46.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(
        Invocation.getter(#initialCoefficientsType),
        returnValue: _i46.InitialCoefficientsType.zeroes,
      ) as _i46.InitialCoefficientsType);

  @override
  _i28.LinkFunction get linkFunction => (super.noSuchMethod(
        Invocation.getter(#linkFunction),
        returnValue: _FakeLinkFunction_26(
          this,
          Invocation.getter(#linkFunction),
        ),
      ) as _i28.LinkFunction);

  @override
  bool get fitIntercept => (super.noSuchMethod(
        Invocation.getter(#fitIntercept),
        returnValue: false,
      ) as bool);

  @override
  num get interceptScale => (super.noSuchMethod(
        Invocation.getter(#interceptScale),
        returnValue: 0,
      ) as num);

  @override
  _i8.Matrix get coefficientsByClasses => (super.noSuchMethod(
        Invocation.getter(#coefficientsByClasses),
        returnValue: _FakeMatrix_6(
          this,
          Invocation.getter(#coefficientsByClasses),
        ),
      ) as _i8.Matrix);

  @override
  num get positiveLabel => (super.noSuchMethod(
        Invocation.getter(#positiveLabel),
        returnValue: 0,
      ) as num);

  @override
  num get negativeLabel => (super.noSuchMethod(
        Invocation.getter(#negativeLabel),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i30.SoftmaxRegressor retrain(_i20.DataFrame? data) => (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeSoftmaxRegressor_28(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i30.SoftmaxRegressor);

  @override
  _i20.DataFrame predictProbabilities(_i20.DataFrame? testFeatures) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictProbabilities,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predictProbabilities,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [SoftmaxRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoftmaxRegressorFactory extends _i1.Mock
    implements _i75.SoftmaxRegressorFactory {
  MockSoftmaxRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i30.SoftmaxRegressor create({
    required _i20.DataFrame? trainData,
    required Iterable<String>? targetNames,
    required _i63.LinearOptimizerType? optimizerType,
    required int? iterationsLimit,
    required double? initialLearningRate,
    required double? decay,
    required int? dropRate,
    required double? minCoefficientsUpdate,
    required double? lambda,
    required int? batchSize,
    required bool? fitIntercept,
    required double? interceptScale,
    required _i51.LearningRateType? learningRateType,
    required bool? isFittingDataNormalized,
    required _i46.InitialCoefficientsType? initialCoefficientsType,
    required num? positiveLabel,
    required num? negativeLabel,
    required bool? collectLearningData,
    required _i43.DType? dtype,
    _i64.RegularizationType? regularizationType,
    _i8.Matrix? initialCoefficients,
    int? randomSeed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #trainData: trainData,
            #targetNames: targetNames,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #lambda: lambda,
            #batchSize: batchSize,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #learningRateType: learningRateType,
            #isFittingDataNormalized: isFittingDataNormalized,
            #initialCoefficientsType: initialCoefficientsType,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #initialCoefficients: initialCoefficients,
            #randomSeed: randomSeed,
          },
        ),
        returnValue: _FakeSoftmaxRegressor_28(
          this,
          Invocation.method(
            #create,
            [],
            {
              #trainData: trainData,
              #targetNames: targetNames,
              #optimizerType: optimizerType,
              #iterationsLimit: iterationsLimit,
              #initialLearningRate: initialLearningRate,
              #decay: decay,
              #dropRate: dropRate,
              #minCoefficientsUpdate: minCoefficientsUpdate,
              #lambda: lambda,
              #batchSize: batchSize,
              #fitIntercept: fitIntercept,
              #interceptScale: interceptScale,
              #learningRateType: learningRateType,
              #isFittingDataNormalized: isFittingDataNormalized,
              #initialCoefficientsType: initialCoefficientsType,
              #positiveLabel: positiveLabel,
              #negativeLabel: negativeLabel,
              #collectLearningData: collectLearningData,
              #dtype: dtype,
              #regularizationType: regularizationType,
              #initialCoefficients: initialCoefficients,
              #randomSeed: randomSeed,
            },
          ),
        ),
      ) as _i30.SoftmaxRegressor);

  @override
  _i30.SoftmaxRegressor fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeSoftmaxRegressor_28(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i30.SoftmaxRegressor);
}

/// A class which mocks [Predictor].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictor extends _i1.Mock implements _i76.Predictor {
  MockPredictor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [LinearRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearRegressorFactory extends _i1.Mock
    implements _i77.LinearRegressorFactory {
  MockLinearRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.LinearRegressor create({
    required _i20.DataFrame? fittingData,
    required String? targetName,
    required _i63.LinearOptimizerType? optimizerType,
    required int? iterationsLimit,
    required _i51.LearningRateType? learningRateType,
    required _i46.InitialCoefficientsType? initialCoefficientsType,
    required double? initialLearningRate,
    required double? decay,
    required int? dropRate,
    required double? minCoefficientsUpdate,
    required double? lambda,
    required bool? fitIntercept,
    required double? interceptScale,
    required int? batchSize,
    required bool? isFittingDataNormalized,
    required bool? collectLearningData,
    required _i43.DType? dtype,
    _i64.RegularizationType? regularizationType,
    int? randomSeed,
    _i8.Matrix? initialCoefficients,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #fittingData: fittingData,
            #targetName: targetName,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #lambda: lambda,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #batchSize: batchSize,
            #isFittingDataNormalized: isFittingDataNormalized,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #randomSeed: randomSeed,
            #initialCoefficients: initialCoefficients,
          },
        ),
        returnValue: _FakeLinearRegressor_29(
          this,
          Invocation.method(
            #create,
            [],
            {
              #fittingData: fittingData,
              #targetName: targetName,
              #optimizerType: optimizerType,
              #iterationsLimit: iterationsLimit,
              #learningRateType: learningRateType,
              #initialCoefficientsType: initialCoefficientsType,
              #initialLearningRate: initialLearningRate,
              #decay: decay,
              #dropRate: dropRate,
              #minCoefficientsUpdate: minCoefficientsUpdate,
              #lambda: lambda,
              #fitIntercept: fitIntercept,
              #interceptScale: interceptScale,
              #batchSize: batchSize,
              #isFittingDataNormalized: isFittingDataNormalized,
              #collectLearningData: collectLearningData,
              #dtype: dtype,
              #regularizationType: regularizationType,
              #randomSeed: randomSeed,
              #initialCoefficients: initialCoefficients,
            },
          ),
        ),
      ) as _i31.LinearRegressor);

  @override
  _i31.LinearRegressor fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeLinearRegressor_29(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i31.LinearRegressor);
}

/// A class which mocks [LinearRegressor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinearRegressor extends _i1.Mock implements _i31.LinearRegressor {
  MockLinearRegressor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i63.LinearOptimizerType get optimizerType => (super.noSuchMethod(
        Invocation.getter(#optimizerType),
        returnValue: _i63.LinearOptimizerType.gradient,
      ) as _i63.LinearOptimizerType);

  @override
  int get iterationsLimit => (super.noSuchMethod(
        Invocation.getter(#iterationsLimit),
        returnValue: 0,
      ) as int);

  @override
  _i51.LearningRateType get learningRateType => (super.noSuchMethod(
        Invocation.getter(#learningRateType),
        returnValue: _i51.LearningRateType.decreasingAdaptive,
      ) as _i51.LearningRateType);

  @override
  _i46.InitialCoefficientsType get initialCoefficientsType =>
      (super.noSuchMethod(
        Invocation.getter(#initialCoefficientsType),
        returnValue: _i46.InitialCoefficientsType.zeroes,
      ) as _i46.InitialCoefficientsType);

  @override
  num get initialLearningRate => (super.noSuchMethod(
        Invocation.getter(#initialLearningRate),
        returnValue: 0,
      ) as num);

  @override
  num get decay => (super.noSuchMethod(
        Invocation.getter(#decay),
        returnValue: 0,
      ) as num);

  @override
  int get dropRate => (super.noSuchMethod(
        Invocation.getter(#dropRate),
        returnValue: 0,
      ) as int);

  @override
  num get minCoefficientsUpdate => (super.noSuchMethod(
        Invocation.getter(#minCoefficientsUpdate),
        returnValue: 0,
      ) as num);

  @override
  num get lambda => (super.noSuchMethod(
        Invocation.getter(#lambda),
        returnValue: 0,
      ) as num);

  @override
  int get batchSize => (super.noSuchMethod(
        Invocation.getter(#batchSize),
        returnValue: 0,
      ) as int);

  @override
  bool get isFittingDataNormalized => (super.noSuchMethod(
        Invocation.getter(#isFittingDataNormalized),
        returnValue: false,
      ) as bool);

  @override
  _i11.Vector get coefficients => (super.noSuchMethod(
        Invocation.getter(#coefficients),
        returnValue: _FakeVector_9(
          this,
          Invocation.getter(#coefficients),
        ),
      ) as _i11.Vector);

  @override
  String get targetName => (super.noSuchMethod(
        Invocation.getter(#targetName),
        returnValue: _i48.dummyValue<String>(
          this,
          Invocation.getter(#targetName),
        ),
      ) as String);

  @override
  bool get fitIntercept => (super.noSuchMethod(
        Invocation.getter(#fitIntercept),
        returnValue: false,
      ) as bool);

  @override
  num get interceptScale => (super.noSuchMethod(
        Invocation.getter(#interceptScale),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i31.LinearRegressor retrain(_i20.DataFrame? data) => (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeLinearRegressor_29(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i31.LinearRegressor);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [DecisionTreeClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecisionTreeClassifier extends _i1.Mock
    implements _i10.DecisionTreeClassifier {
  MockDecisionTreeClassifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  num get minError => (super.noSuchMethod(
        Invocation.getter(#minError),
        returnValue: 0,
      ) as num);

  @override
  int get minSamplesCount => (super.noSuchMethod(
        Invocation.getter(#minSamplesCount),
        returnValue: 0,
      ) as int);

  @override
  int get maxDepth => (super.noSuchMethod(
        Invocation.getter(#maxDepth),
        returnValue: 0,
      ) as int);

  @override
  _i35.TreeAssessorType get assessorType => (super.noSuchMethod(
        Invocation.getter(#assessorType),
        returnValue: _i35.TreeAssessorType.majority,
      ) as _i35.TreeAssessorType);

  @override
  num get positiveLabel => (super.noSuchMethod(
        Invocation.getter(#positiveLabel),
        returnValue: 0,
      ) as num);

  @override
  num get negativeLabel => (super.noSuchMethod(
        Invocation.getter(#negativeLabel),
        returnValue: 0,
      ) as num);

  @override
  Iterable<String> get targetNames => (super.noSuchMethod(
        Invocation.getter(#targetNames),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i43.DType get dtype => (super.noSuchMethod(
        Invocation.getter(#dtype),
        returnValue: _i43.DType.float32,
      ) as _i43.DType);

  @override
  _i57.Future<_i16.File> saveAsSvg(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsSvg,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsSvg,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i57.Future<String> saveToStore(
    _i78.TreeStore? store, {
    String? treeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToStore,
          [store],
          {#treeId: treeId},
        ),
        returnValue: _i57.Future<String>.value(_i48.dummyValue<String>(
          this,
          Invocation.method(
            #saveToStore,
            [store],
            {#treeId: treeId},
          ),
        )),
      ) as _i57.Future<String>);

  @override
  double assess(
    _i20.DataFrame? observations,
    _i39.MetricType? metricType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assess,
          [
            observations,
            metricType,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i57.Future<_i16.File> saveAsJson(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #saveAsJson,
          [filePath],
        ),
        returnValue: _i57.Future<_i16.File>.value(_FakeFile_14(
          this,
          Invocation.method(
            #saveAsJson,
            [filePath],
          ),
        )),
      ) as _i57.Future<_i16.File>);

  @override
  _i10.DecisionTreeClassifier retrain(_i20.DataFrame? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrain,
          [data],
        ),
        returnValue: _FakeDecisionTreeClassifier_8(
          this,
          Invocation.method(
            #retrain,
            [data],
          ),
        ),
      ) as _i10.DecisionTreeClassifier);

  @override
  _i20.DataFrame predictProbabilities(_i20.DataFrame? testFeatures) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictProbabilities,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predictProbabilities,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);

  @override
  _i20.DataFrame predict(_i20.DataFrame? testFeatures) => (super.noSuchMethod(
        Invocation.method(
          #predict,
          [testFeatures],
        ),
        returnValue: _FakeDataFrame_18(
          this,
          Invocation.method(
            #predict,
            [testFeatures],
          ),
        ),
      ) as _i20.DataFrame);
}

/// A class which mocks [LogisticRegressorFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogisticRegressorFactory extends _i1.Mock
    implements _i79.LogisticRegressorFactory {
  MockLogisticRegressorFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i29.LogisticRegressor create({
    required _i20.DataFrame? trainData,
    required String? targetName,
    required _i63.LinearOptimizerType? optimizerType,
    required int? iterationsLimit,
    required double? initialLearningRate,
    required double? decay,
    required int? dropRate,
    required double? minCoefficientsUpdate,
    required double? probabilityThreshold,
    required double? lambda,
    required int? batchSize,
    required bool? fitIntercept,
    required double? interceptScale,
    required bool? isFittingDataNormalized,
    required _i51.LearningRateType? learningRateType,
    required _i46.InitialCoefficientsType? initialCoefficientsType,
    required num? positiveLabel,
    required num? negativeLabel,
    required bool? collectLearningData,
    required _i43.DType? dtype,
    _i64.RegularizationType? regularizationType,
    _i11.Vector? initialCoefficients,
    int? randomSeed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #trainData: trainData,
            #targetName: targetName,
            #optimizerType: optimizerType,
            #iterationsLimit: iterationsLimit,
            #initialLearningRate: initialLearningRate,
            #decay: decay,
            #dropRate: dropRate,
            #minCoefficientsUpdate: minCoefficientsUpdate,
            #probabilityThreshold: probabilityThreshold,
            #lambda: lambda,
            #batchSize: batchSize,
            #fitIntercept: fitIntercept,
            #interceptScale: interceptScale,
            #isFittingDataNormalized: isFittingDataNormalized,
            #learningRateType: learningRateType,
            #initialCoefficientsType: initialCoefficientsType,
            #positiveLabel: positiveLabel,
            #negativeLabel: negativeLabel,
            #collectLearningData: collectLearningData,
            #dtype: dtype,
            #regularizationType: regularizationType,
            #initialCoefficients: initialCoefficients,
            #randomSeed: randomSeed,
          },
        ),
        returnValue: _FakeLogisticRegressor_27(
          this,
          Invocation.method(
            #create,
            [],
            {
              #trainData: trainData,
              #targetName: targetName,
              #optimizerType: optimizerType,
              #iterationsLimit: iterationsLimit,
              #initialLearningRate: initialLearningRate,
              #decay: decay,
              #dropRate: dropRate,
              #minCoefficientsUpdate: minCoefficientsUpdate,
              #probabilityThreshold: probabilityThreshold,
              #lambda: lambda,
              #batchSize: batchSize,
              #fitIntercept: fitIntercept,
              #interceptScale: interceptScale,
              #isFittingDataNormalized: isFittingDataNormalized,
              #learningRateType: learningRateType,
              #initialCoefficientsType: initialCoefficientsType,
              #positiveLabel: positiveLabel,
              #negativeLabel: negativeLabel,
              #collectLearningData: collectLearningData,
              #dtype: dtype,
              #regularizationType: regularizationType,
              #initialCoefficients: initialCoefficients,
              #randomSeed: randomSeed,
            },
          ),
        ),
      ) as _i29.LogisticRegressor);

  @override
  _i29.LogisticRegressor fromJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeLogisticRegressor_27(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i29.LogisticRegressor);
}
